### ISSUE TITLE
Fix the syntax highlighter

### ISSUE THREAD

**Issue by mark-wiemer** [mark-wiemer-org/ahkpp#128]
Part of epic issue #123

The syntax highlighter uses the standard VS Code TextMate grammar syntax, but it's incorrect. (See #124: Pasting the code snippet into VS Code, the `]` is wrongly styled as invalid/red. TODO provide more examples)

This issue tracks work to improve, test, and publish a much better syntax highlighter for both AHK v1 and AHK v2.

- [ ] Understand [@lexikos' Lua syntax highlighters](https://www.autohotkey.com/boards/viewtopic.php?p=467274&sid=120f9e08df08b152935c063e4c1331b0#p467274) -- rather blocked, see https://github.com/Lexikos/Scintillua-ahk/issues/1
  - [ ] Run them locally
  - [ ] Add unit tests
  - [ ] See how they handle problematic code in this repo
- [ ] Translate into a tested TextMate grammar
- [ ] Merge with main

Other things to research:

- [highlight.js](https://github.com/highlightjs/highlight.js/blob/fd307015164c05b191156efc378622293089c616/src/languages/autohotkey.js)
- [SciTE4AutoHotkey lexer logic](https://github.com/fincs/SciTE4AutoHotkey/issues/42)
- [SublimeAutoHotkey](https://github.com/ahkscript/SublimeAutoHotkey/blob/master/AutoHotkey.tmLanguage), can be easily converted using online tools like [wtools.io](https://wtools.io/convert-plist-to-json)
- [Sublime grammar scope naming docs](https://www.sublimetext.com/docs/scope_naming.html)
- [PrismJS](https://github.com/PrismJS/prism/blob/master/components/prism-autohotkey.js)
- [NekoHelp](https://github.com/CoffeeChaton/vscode-autohotkey-NekoHelp)
- [Language server protocol](https://github.com/thqby/vscode-autohotkey2-lsp)

**Comment by mark-wiemer** [comment]
I could write a YAML grammar... that sounds fun! [Syntax highlighting guide](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) - see "Using YAML to write a grammar" section

**Comment by mark-wiemer** [comment]
Officially got the YAML grammar up and running, along with unit tests to ensure the grammar is working as expected. After lots of engineering hygiene work on vscode-helloworld, I'm ready to hit the ground running :)

**Comment by anonymous1184** [comment]
Like I've said, a couple of weeks I revisited my project where I was working on the fixes and thought I was doing a rather poor job. I then followed your steps and learned about the topic a bit before jumping into the action... yep, I was doing it all wrong.

I don't know how the formatting works but seems like it's based on the tokenization left by the syntax highlighter, therein lies the issue. The current version is very basic and there are parts where any scope is used as long as it matches a certain color\*. In other words; if the tokenization is based on the highlighter, needs serious work (as in dump it and start from scratch).

<sup>*\* Like the word-operators on legacy conditionals.*</sup>

What's needed is to properly define and delimit each scope and make sure you are not including extra spacing, also account for the peculiarities of the language so when the formatting is invoked those are taken into account (stuff like the period being an accessor and an operand for concatenation while it can be a continuation just like the comma and stuff more obvious like the specialized loops and the fact that only accept Allman and not K&R).

I started to write the `.tmLanguage` from scratch and dismiss it a few times because as soon as I made some progress I realized that there were betters ways to implement less and more reusable rules, effectively cascading them to make proper and cohesive tokenization.

I'm gonna link an image because is very long and putting it inline is kinda weird as it takes over.

[Image][1] - The column on the left beside the proper scopes has different colors that helped me to see what I was doing, the column in the middle is how is supposed to look and the right column is the current version. Also for this, I've disabled the bracket pair colorization and the bracket pairs lines (horizontal/vertical).

As you can see there are a lot of inconsistencies in the current version, and if the formatting is carried out after the tokenization of the highlighter, by fixing the highlighter many of the issues in the formatter will be addressed. 

The penultimate region has a `TODO` item, to be highlighted as unquoted text when needed and the last region is just hard-coded as how commands should look.

And of course, there are lots to be done like the rest of the specialized loops and group commands depending on which position they use keywords to avoid highlighting input/output arguments sharing the name with parameters. But I guess that's a starting point for you to see where the current highlighter has weaknesses, most of them because AHK has an awful lot of peculiarities that you only get to know once you have a few years working with it.

There are also missing functions/commands and some commands with deprecated syntax as default. I parsed the CHM help file with AHK itself but I guess you can do the same with documentation repository by parsing the DOM to keep the description and placeholders of the commands up to date.

Thanks a lot for cleaning this up as it was in dire need!

[1]: https://user-images.githubusercontent.com/53758552/176288046-ca6f37e4-332f-49fc-b05a-f1b47d730121.png

**Comment by mark-wiemer** [comment]
Thanks so much @anonymous1184, this research is really helpful.

As a long-time AHK user, I'd greatly appreciate your insights on the quirks of AHK. Honestly I've only written ~200 lines of AHK, so my current goal is to understand the syntax, its quirks, and how to tokenize it so that I can update [📄 `syntaxes/ahk.tmLanguage.yaml`](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/blob/main/syntaxes/ahk.tmLanguage.yaml)

Feel free to create many smaller issues with small files that have syntax highlight issues in them, and you can propose the correct color / theme / scope if you really want a 🌟 gold star 🌟 (see scopes [naming conventions](https://macromates.com/manual/en/language_grammars#naming_conventions)) Remember to inspect scope using `Developer: Inspect Editor Tokens and Scopes` from the command palette (F1). You can also clone the repo and create some test cases in [📁 `src/test/suite/grammar/samples`](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/tree/main/src/test/suite/grammar/samples). That'd be much appreciated so that we can make sure that as we tweak the grammar we don't break things that are working well :) 

As always, I'm here to help. I'm a bit busy this week but hoping to come back to this project during the long weekend. Let me know if you need anything.

**Comment by mark-wiemer** [comment]
Also, @anonymous1184 , you can paste long block of text or images inside a [`<details>` tag in Markdown](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab), e.g.

```
<details>
Hello world
<details>
```

Becomes

<details>
Hello world
<details>

Fancy!

**Comment by anonymous1184** [comment]
I know about the tags in Markdown, but I felt like saving the file to see it on a vertical monitor was more appropriate.

Regarding the scopes, what helped me a lot was the [Sublime Text Documentation][1], but yeah I gave a few reads to the TextMate documentation as well and everything was checked against the Tokens/Scopes Inspector (the main reason why I used extra coloring/scoping to visually differentiate).

I can share the `.tmLanguage.json` file I've been working on\*, the difference as I've said is how it cascades basically rendering the current highlighting obsolete. For example, there are a lot of negative lookaheads for `MsgBox`; and I get the why, so the command can be used as debug (weird flex in the debug extension). Also I tried to optimize a little the expressions by reducing the matching steps (doesn't hurt, right?), so the lists also won't match.

<sup>*\* What I've been doing is very artisanal/rustic: directly editing the JSON and then checking in VSCode with the inspector, don't know if there's any better method.*</sup>

As for splitting into smaller cases... I guess that's the issue, there are many exceptions one based in the other and unless everything is put together you cannot see if the end result is the appropriate, hence the very large image to see everything at once (I don't know if that makes sense, English is not my first language).

But let's try, I'll add a single issue so you can see if that works for you. If not, I can always ditch it and start from scratch so whatever I do can be easily integrated into your workflow. Let me know if any helps you.

[1]: https://www.sublimetext.com/docs/scope_naming.html

**Comment by mark-wiemer** [comment]
Hey @anonymous1184 , I've merged #143 which should make it easy to report bugs :)

I'd love to see your JSON file, it'd be great for me to work on.

I've also updated the test docs, see #144, hopefully this answers some of your questions about my process.

**Comment by mark-wiemer** [comment]
This ought to help: https://github.com/highlightjs/highlight.js/blob/fd307015164c05b191156efc378622293089c616/src/languages/autohotkey.js

**Comment by mark-wiemer** [comment]
See https://github.com/Lexikos/Scintillua-ahk/issues/1

**Comment by mark-wiemer** [comment]
Another grammar candidate: [SublimeAutoHotkey](https://github.com/ahkscript/SublimeAutoHotkey/blob/master/AutoHotkey.tmLanguage)

**Comment by anonymous1184** [comment]
Just by a simple glance you can tell is the same.

There's no way around it, you either keep the one with the issues or write one from scratch. However I don't know what's the next step if you implement LSP... what's the role syntax highlighting plays?

**Comment by mark-wiemer** [comment]
Hey @anonymous1184, I hope things are going well for you. Obviously the Ukraine situation isn't any better, but I hope you're safe and able to get through the days.

FYI, I will be returning to this issue now that my life has calmed down a bit too :) happy to discuss, though I can say I don't know much about language server protocol yet, just that it's a standard built by Microsoft that should be able to solve some of our problems if we choose to rebuild from the ground up. I've added some more research links in the issue description of things I'll be looking into in the short term.

**Comment by mark-wiemer** [comment]
Specific issues and labels will be used for tracking, not general issues like this one.

**Comment by LaserMade** [comment]
Hi all,

Does anyone know if there is any work being done on AHK v2 syntax highlighting for highlight.js? Specifically, I'm trying to highlight AHK v2 syntax within Quill.js. 

I see that it was briefly mentioned at the top but that's all.

**Comment by kyklish** [comment]
> Hi all,
> 
> Does anyone know if there is any work being done on AHK v2 syntax highlighting for highlight.js? Specifically, I'm trying to highlight AHK v2 syntax within Quill.js. 
> 
> I see that it was briefly mentioned at the top but that's all.

https://github.com/mark-wiemer-org/ahkpp/discussions/21#discussioncomment-9717144

Another extension has much better support of AHK v2. Look at bundle, proposed by Mark.

**Comment by mark-wiemer** [comment]
I haven't focused on this, but I can say my passion is in syntax highlighting. I'm familiar with Quill.js but we'd need to parse the grammar with a JavaScript library to get it working, I haven't researched that side of things.

That said, I'll be contributing to thqby's extension instead of adding v2 support to this repo, as that extension already has better support and an extension pack is easy to implement. So be sure to follow that one for updates.
