### ISSUE TITLE
No formatter AHK2 script in VS Code

### ISSUE THREAD

**Issue by tirosko** [mark-wiemer-org/ahkpp#444]
## Description
After Ctrl+Shilt+P (open palete - Format document.
Appear request to install formatter

Please see attached file.

Contact mail: tibor.rosko@hotmail.com
![Snímka obrazovky 2024-05-26 125746](https://github.com/mark-wiemer-org/ahkpp/assets/48452196/593707ce-aa3b-4ce4-bef8-f297fd64a921)

**Comment by mark-wiemer** [comment]
Ref #445, let me know if this helps :)

**Comment by tirosko** [comment]
With rename extension by script name from ahk to ahk1 work formatter.

Thanks for help.

Tibor Roško
SNP 23
900 01 Modra
mobil: 0903445532

**Comment by Lootwig** [comment]
That assigns the v1 _type_ though, shouldn't the "ahk2" type still be picked up by VS Code? I can't even assign an unsupported formatter to the type, I still get the "no installed formatter" box

```json
// settings.json
{
  "files.associations": {
    "*.ahk": "ahk2"
  },
  "[ahk2]": {
    "editor.defaultFormatter": "mark-wiemer.vscode-autohotkey-plus-plus"
  },
}
```

**Comment by mark-wiemer** [comment]
I understand the frustration, and I'll go ahead and enable experimental v2 support to unblock simple scripts, but please be aware that there will be many, many bugs noticeable on larger scripts. Ref #381 for details.

**Comment by Lootwig** [comment]
@mark-wiemer relax, the frustration is within reasonable limits :D

The main inconvenience isn't really the wip-status of v2, but the fact that the extension _recognizes_ the language, VS code _lists_ ahk++ after offering to search for formatters, and I spent an embarrassing amount of time trying to figure out why the message is "no installed formatter" even after manual assignment, instead of something more specific like when attempting to assign the "dart" formatter:

![image](https://github.com/mark-wiemer-org/ahkpp/assets/39827040/9e5f5cab-0b28-42c2-b2d9-16d10f56ddf2)

It might be commonly known that "contributing a language" and having "formatters" as one of the categories of an extension may not mean there's a formatter for _all_ contributed languages - I just didn't know and if you feel like language support just isn't ready enough, simply disabling the ahk2 type would be a totally acceptable remedy for the cause of my confusion!

**Comment by mark-wiemer** [comment]
Let me see if there's an easy way around this. I don't think it's as simple as "disabling the ahk2 type" as I do want to keep that: the extension uses the type to determine which AHK runtime to use and which icon to render (blue for v1, green for v2). I found this and am investigating now:

https://github.com/microsoft/vscode/blob/d2d053d84e2460661c435ac825b1b1895f7efd51/src/vs/workbench/contrib/format/browser/formatActionsMultiple.ts#L130

**Comment by mark-wiemer** [comment]
Hmm, @Lootwig I'm not able to reproduce your issue:

![image](https://github.com/mark-wiemer-org/ahkpp/assets/7833360/c897e7e5-9bda-4e06-afaf-965bdd3028e0)


```jsonc
// settings.json
"[ahk2]": {
  "editor.defaultFormatter": "mark-wiemer.vscode-autohotkey-plus-plus"
},
```

For now I'm not seeing anything wrong with the extension. There is a bit of AHK v2 support, but I'll try to update the readme to be clearer about the limitations. I am working towards adding full formatting support though :)
