### ISSUE TITLE
IntelliSense: Unchecking the setting has no effect

### ISSUE THREAD

**Issue by fade2gray** [mark-wiemer-org/ahkpp#48]
**Describe the bug**

Assuming that IntelliSense is responsible for 'autocomplete' and detailed descriptions of functions etc., toggling the setting on/off seems not to have any effect after reload.

**To Reproduce**

1. Go to 'AutoHotkey Plus Plus settings'
2. Uncheck 'Enable IntelliSense (Preview). Changes take effect after reload.'
3. Reload 'F1 - Developer: Reload Window'
4. Test script for autocomplete and/or descriptive tooltips.

**Expected behavior**

IntelliSense to be disabled.

**Additional context**

Should Reload and Shutdown/Restart have the same effect (Ref: #39)- neither make any difference after unchecking IntelliSense.

**Comment by mark-wiemer** [comment]
Good catch, I broke this while renaming stuff earlier, I think

**Comment by fade2gray** [comment]
@mark-wiemer I'd like to re-raise this, as disabling intellisense in the settings has never worked for me, unless I'm totally misunderstanding just exactly what it's supposed to disable.

A before and after example, perhaps?

**Comment by mark-wiemer** [comment]
Acknowledging. I do remember IntelliSense makes very little difference currently, but there is a difference in my experience. I'll see if I can get some screenshots for documentation and testing :)

**Comment by mark-wiemer** [comment]
Note that you must restart VS Code after toggling the setting to see any difference :)

Try toggling IntelliSense (IS) with this template:

```ahk
; Something cool
myFunc() {
}
```

Then type `m`. With IS off, it'll suggest `myFunc` only because it occurs elsewhere in the file. With IS on, it'll suggest it and also tell you the function name. This applies to all functions in the current folder and all variables in the current file.

Off:
![image](https://github.com/mark-wiemer-org/ahkpp/assets/7833360/faae9bcf-c53c-405f-9669-b5e86d8fa26e)


On:
![image](https://github.com/mark-wiemer-org/ahkpp/assets/7833360/5b57cbfa-903f-4741-af4d-edf695fe7748)


Closing this one as complete, please re-open if you're having issues :)
